const scheduleData={weekday:[['6:00 AM','Early BJJ','Mon / Wed / Fri · all-level gi','All levels'],['6:00 AM','Early No-Gi','Tue / Thu','All levels'],['5:30 PM','Kids Program','Mon / Wed BJJ · Tue / Thu Muay Thai','Kids'],['7:30 PM','No-Gi BJJ','Tuesday / Thursday evenings','All levels']],saturday:[['9:00 AM','Muay Thai','Striking class','All levels'],['10:00 AM','Fundamental BJJ','Family class','Fundamentals'],['10:00 AM','Kids BJJ','Family class','Kids'],['11:00 AM','BJJ','All-level gi','All levels']],sunday:[['8:00 AM','Competition Class','Focused competition training','Competitors'],['12:00 PM','Boxing','Technical boxing class','All levels']]};
const panel=document.querySelector('#schedule-panel');
function renderSchedule(day){panel.innerHTML=scheduleData[day].map(x=>`<article class="class-row"><time>${x[0]}</time><div><h3>${x[1]}</h3><p>${x[2]}</p></div><span>${x[3]}</span></article>`).join('')}
renderSchedule('weekday');
document.querySelectorAll('.day-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.day-tab').forEach(t=>{t.classList.remove('active');t.setAttribute('aria-selected','false')});tab.classList.add('active');tab.setAttribute('aria-selected','true');renderSchedule(tab.dataset.day)}));
const navToggle=document.querySelector('.nav-toggle'),nav=document.querySelector('.main-nav');navToggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');navToggle.setAttribute('aria-expanded',String(open))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');navToggle.setAttribute('aria-expanded','false')}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));

const widget=document.querySelector('.chat-widget'),launcher=document.querySelector('.chat-launcher'),closeChat=document.querySelector('.chat-close'),messages=document.querySelector('#chat-messages'),form=document.querySelector('#chat-form'),input=document.querySelector('#chat-input'),suggestions=document.querySelector('#chat-suggestions');
function setChat(open){widget.classList.toggle('open',open);widget.setAttribute('aria-hidden',String(!open));launcher.setAttribute('aria-expanded',String(open));document.body.classList.toggle('chat-open',open&&innerWidth<650);if(open)setTimeout(()=>input.focus(),220)}
launcher.addEventListener('click',()=>setChat(true));closeChat.addEventListener('click',()=>setChat(false));document.querySelectorAll('.ask-buma').forEach(b=>b.addEventListener('click',()=>setChat(true)));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&widget.classList.contains('open'))setChat(false)});
const stop=new Set('a an and are as at be by can do does for from how i in is it me my of on or our the their there this to what when where which who with you your'.split(' '));
const aliases={'brazilian jiu jitsu':'bjj','jiu-jitsu':'bjj','jiu jitsu':'bjj','no-gi':'no gi','nogi':'no gi','children':'kids','child':'kids','youth':'kids','teacher':'instructor','trainers':'instructor','coaches':'instructor','fees':'price','rates':'price','hours':'schedule'};
function normalize(text){let out=text.toLowerCase();Object.entries(aliases).forEach(([a,b])=>out=out.replaceAll(a,b));return out.replace(/[^a-z0-9:\s]/g,' ').replace(/\s+/g,' ').trim()}
function retrieve(query){const q=normalize(query),terms=q.split(' ').filter(w=>w.length>1&&!stop.has(w));return BUMA_KNOWLEDGE.map(doc=>{const hay=normalize(`${doc.title} ${doc.text} ${doc.keywords.join(' ')}`);let score=0;terms.forEach(t=>{if(doc.keywords.some(k=>normalize(k)===t))score+=4;if(normalize(doc.title).includes(t))score+=3;if(hay.includes(t))score+=1});doc.keywords.forEach(k=>{if(q.includes(normalize(k))&&normalize(k).includes(' '))score+=7});if(q.includes('schedule')&&doc.category==='schedule')score+=2;if((q.includes('beginner')||q.includes('new'))&&doc.id==='overview')score+=6;return{...doc,score}}).filter(d=>d.score>0).sort((a,b)=>b.score-a.score).slice(0,3)}
function compose(query,docs){const q=normalize(query);if(!docs.length)return `I couldn't find that in the academy information I have. I can reliably help with programs, published class times, instructors, location, reviews and contact details. For anything else, call the official-site number at (716) 671-7197.`;
  if(q.includes('beginner')||q.includes('never trained')||q.includes('new'))return `Yes—BUMA explicitly says its programs serve all skill levels, from beginners to seasoned martial artists. A fundamentals class is a sensible entry point, and the published schedule includes Fundamental BJJ plus all-level sessions. Call ahead so the academy can match your goals to the best first class.`;
  if(q.includes('price')||q.includes('cost')||q.includes('membership')||q.includes('trial'))return `Current prices aren't published on the official pages I reviewed, and I don't want to guess. Ask the academy directly about membership rates, trial availability and any sibling or family options: (716) 671-7197 or info@fightfamily.com.`;
  if(q.includes('phone')||q.includes('number')||q.includes('contact'))return `The current official site displays (716) 671-7197 and info@fightfamily.com. One detail to know: its click-to-call link—and the Google listing provided for this project—uses (716) 563-0720. Because both are published, try the displayed official-site number first and use the Maps number as an alternate.`;
  if(q.includes('schedule')&&docs.length>1)return `Here are the most relevant published times: ${docs.map(d=>d.text).join(' ')} Because schedules can change, confirm before your first visit.`;
  return `${docs[0].text}${docs[0].category==='schedule'?' Because schedules can change, confirm before your first visit.':''}`}
function appendMessage(text,role,docs=[]){const wrap=document.createElement('div');wrap.className=`message ${role}`;const p=document.createElement('p');p.textContent=text;wrap.appendChild(p);messages.appendChild(wrap);if(role==='assistant'&&docs.length){const sources=document.createElement('div');sources.className='source-list';[...new Map(docs.map(d=>[d.url,d])).values()].forEach(d=>{const a=document.createElement('a');a.href=d.url;a.target='_blank';a.rel='noopener';a.textContent=`Source: ${d.source}`;sources.appendChild(a)});messages.appendChild(sources)}messages.scrollTop=messages.scrollHeight}
function ask(question){const clean=question.trim();if(!clean)return;appendMessage(clean,'user');input.value='';suggestions.style.display='none';const typing=document.createElement('div');typing.className='message assistant typing';typing.innerHTML='<p>•••</p>';messages.appendChild(typing);messages.scrollTop=messages.scrollHeight;setTimeout(()=>{typing.remove();const docs=retrieve(clean);appendMessage(compose(clean,docs),'assistant',docs)},450)}
form.addEventListener('submit',e=>{e.preventDefault();ask(input.value)});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}});input.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,90)+'px'});suggestions.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>ask(b.textContent)));
