export const BUMA_KNOWLEDGE = [
  {id:'overview',title:'Academy overview',category:'about',text:'Buffalo United Martial Arts, also called BUMA, offers martial arts training in downtown Buffalo. The official site describes Brazilian Jiu-Jitsu, Muay Thai, MMA and fitness as core offerings and says programs welcome beginners through seasoned martial artists.',keywords:['about','overview','beginner','new','experience','programs','classes','fitness'],source:'Official BUMA home',url:'https://buffalounitedmartialarts.com/home'},
  {id:'programs',title:'Programs offered',category:'programs',text:'Published offerings include Brazilian Jiu-Jitsu for all levels, fundamentals, kids and competition; adult and kids Muay Thai; MMA; submission wrestling/no-gi; boxing; Judo; Sambo; and Kru Fit Cardio.',keywords:['program','class','bjj','jiu jitsu','muay thai','mma','wrestling','boxing','judo','sambo','kru fit','cardio'],source:'Official BUMA programs & FAQ',url:'https://buffalounitedmartialarts.com/home#section-cWOGbHw24Y'},
  {id:'bjj',title:'Brazilian Jiu-Jitsu',category:'programs',text:'BUMA presents BJJ as a grappling art that uses technique and leverage, including ground control, joint locks and chokes. The academy publishes all-level, fundamentals, kids, competition, gi and no-gi sessions.',keywords:['bjj','brazilian jiu jitsu','grappling','gi','no gi','submission','ground'],source:'Official BUMA programs',url:'https://buffalounitedmartialarts.com/home#section-cWOGbHw24Y'},
  {id:'kids',title:'Kids classes',category:'schedule',text:'Published kids times are Kids BJJ on Mondays and Wednesdays at 5:30 PM, Kids Muay Thai on Tuesdays and Thursdays at 5:30 PM, and a Saturday Kids BJJ family class at 10 AM. The academy says kids classes emphasize discipline, teamwork, confidence, focus, resilience and safe fundamentals.',keywords:['kid','kids','child','children','youth','family','monday','wednesday','tuesday','thursday','saturday','5:30','10 am'],source:'Official BUMA FAQ',url:'https://buffalounitedmartialarts.com/home#section-yZGtLLFL3R'},
  {id:'morning',title:'Early morning BJJ',category:'schedule',text:'The official FAQ publishes 6 AM BJJ Monday through Friday: all-level gi on Monday, Wednesday and Friday; no-gi on Tuesday and Thursday.',keywords:['early','morning','6 am','weekday','monday','tuesday','wednesday','thursday','friday','gi','no gi'],source:'Official BUMA FAQ',url:'https://buffalounitedmartialarts.com/home#section-yZGtLLFL3R'},
  {id:'weekend',title:'Weekend schedule',category:'schedule',text:'Saturday published classes are Muay Thai at 9 AM, Fundamental BJJ family class and Kids BJJ family class at 10 AM, and all-level gi BJJ at 11 AM. Sunday published classes are Competition Class at 8 AM and Boxing at 12 PM.',keywords:['weekend','saturday','sunday','9 am','10 am','11 am','8 am','12 pm','boxing','competition','family'],source:'Official BUMA FAQ',url:'https://buffalounitedmartialarts.com/home#section-yZGtLLFL3R'},
  {id:'nogi',title:'No-gi schedule',category:'schedule',text:'Published no-gi classes include Tuesday and Thursday at 6 AM, Tuesday and Thursday evenings at 7:30 PM, and fundamental Submission Wrestling on Monday at 8 PM.',keywords:['no gi','nogi','submission wrestling','tuesday','thursday','monday','6 am','7:30','8 pm'],source:'Official BUMA FAQ',url:'https://buffalounitedmartialarts.com/home#section-yZGtLLFL3R'},
  {id:'other-times',title:'Judo, boxing and conditioning times',category:'schedule',text:'The official FAQ publishes Judo on Tuesdays at 8 PM, Kru Fit Cardio on Tuesdays and Thursdays at 4 PM, and Boxing on Sundays at 12 PM.',keywords:['judo','kru fit','cardio','boxing','tuesday','thursday','sunday','8 pm','4 pm','12 pm'],source:'Official BUMA FAQ',url:'https://buffalounitedmartialarts.com/home#section-yZGtLLFL3R'},
  {id:'coaches',title:'Instructor team',category:'people',text:'The official site names Josh Ketry for BJJ, Khru Keith Forant for Muay Thai and youth programs, Larry Backlas for BJJ, Anthony Gugino for Judo and grappling, Michael Christopher for boxing, and Jon Kokotajlo for Sambo.',keywords:['coach','coaches','instructor','teacher','teaches','teach','josh','ketry','keith','forant','larry','backlas','anthony','gugino','michael','christopher','jon','kokotajlo'],source:'Official BUMA instructors',url:'https://buffalounitedmartialarts.com/home#section-NQKsV4K2wr'},
  {id:'affiliation',title:'Affiliation and community',category:'about',text:'BUMA states that it has been a proud member of Essential BJJ under Professor JT Torres since 2021. The official site also links to the We Defy Foundation.',keywords:['essential','affiliation','jt torres','we defy','veteran','foundation','lineage'],source:'Official BUMA footer',url:'https://buffalounitedmartialarts.com/home'},
  {id:'location',title:'Location and directions',category:'contact',text:'The academy is at 359 Ganson Street, Buffalo, New York 14203, in the Buffalo RiverWorks area in downtown Buffalo.',keywords:['where','location','address','directions','ganson','riverworks','downtown','parking','buffalo'],source:'Official contact page',url:'https://buffalounitedmartialarts.com/contact-us'},
  {id:'contact',title:'Official contact information',category:'contact',text:'The current official site displays phone number (716) 671-7197 and email info@fightfamily.com. Its click-to-call link and the Google Maps listing supplied for this project use (716) 563-0720, so visitors should be aware that two numbers are published.',keywords:['phone','call','number','contact','email','fightfamily','563','671'],source:'Official BUMA contact page',url:'https://buffalounitedmartialarts.com/contact-us'},
  {id:'reviews',title:'Public reputation',category:'reviews',text:'The Google listing information supplied for this project reports a 4.9 rating from 35 reviews. Review themes emphasize welcoming instructors, a family atmosphere, learning, clean facilities, technical knowledge and options for both adults and children.',keywords:['review','rating','stars','reputation','good','welcoming','clean','atmosphere','family'],source:'Google Business profile (project brief)',url:'https://www.google.com/maps/search/?api=1&query=Buffalo+United+Martial+Arts+Academy+359+Ganson+St+Buffalo+NY'},
  {id:'pricing',title:'Pricing and trials',category:'membership',text:'The official pages reviewed do not publish current membership prices or a confirmed current free-trial policy. Contact the academy directly for up-to-date rates, trial availability, sibling or family pricing and enrollment details.',keywords:['price','pricing','cost','membership','fee','trial','free class','discount','sibling','family plan','join','enroll'],source:'Official BUMA contact page',url:'https://buffalounitedmartialarts.com/contact-us'}
];
